---
# DINO ARGS
# model
arch: "vit_tiny"
checkpoint_path: "/mnt/cluster/data_hdd/jazibmodels/dino_vitbase16_pretrain_bench_github.pth"
checkpoint_key: "teacher"
patch_size: 16
# data
data_path: "/home/jazib/projects/data/gartow_seg/single_class_sliced/8020/"
crop_size: 224
# segmentation specific
reduce_dim: 112
n_heads: 4
complex_trans_conv: True
freeze_backbone: True
# lightning
lr: 0.001
batch_size: 32
num_workers: 8
# training
output_dir: "./bench_unet/"
max_epochs: 500
resume: False
resume_ckpt: null
