---
# DINO ARGS
# model
arch: "vit_tiny"
checkpoint_path:  "/mnt/cluster/data_hdd/jazibmodels/dino_vitbase16_pretrain_bench_github.pth"
checkpoint_key: "teacher"
patch_size: 16
num_classes: 10
linear_eval: False
# data
data_path: "/home/jazib/projects/data/gartow_class_ttv/"
input_size: 96
# lightning
lr: 0.00001
batch_size: 32
num_workers: 8
# training
output_dir: "./bench_dino_class/"
max_epochs: 100
resume: False
resume_ckpt: null
